name: my_playground
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  geojson: ^0.9.1
  csv: ^4.1.0
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
