---
title: "Agrupamiento"
output: pdf_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library(vegan)

knitr::opts_chunk$set(echo = TRUE)
```

Lectura de conjunto de datos
```{r}
accidentalidad = read.csv("./incidentes_medellin_con_fechas.csv", header = TRUE)
```


Adecuacion del conjunto de datos
```{r}
# Eliminar variables que no se usaran
accidentalidad$X.1 = NULL
accidentalidad$X = NULL
accidentalidad$Y = NULL
accidentalidad$OBJECTID = NULL
accidentalidad$RADICADO = NULL
accidentalidad$HORA = NULL
accidentalidad$DIA = NULL
accidentalidad$CBML = NULL
accidentalidad$MES = NULL
accidentalidad$PERIODO = NULL
accidentalidad$DIRECCION = NULL
accidentalidad$DIRECCION_ENC = NULL
accidentalidad$X_MAGNAMED = NULL
accidentalidad$Y_MAGNAMED = NULL
accidentalidad$LONGITUD = NULL
accidentalidad$LATITUD = NULL

# Todos los festivos y fechas importantes en una misma variable
accidentalidad["FECHA_IMPORTANTE"] = accidentalidad$puente_festivo + accidentalidad$puente_reyes + accidentalidad$semana_santa + accidentalidad$puente_semana_santa + accidentalidad$receso_mitad + accidentalidad$feria_flores + accidentalidad$receso_octubre + accidentalidad$vacaciones_final + accidentalidad$festivo_entre_semana + accidentalidad$no_festivo_importante

accidentalidad["FECHA_IMPORTANTE"] = ifelse(accidentalidad["FECHA_IMPORTANTE"] > 0, 1, 0)

accidentalidad$puente_festivo = NULL
accidentalidad$puente_reyes = NULL
accidentalidad$semana_santa = NULL
accidentalidad$puente_semana_santa = NULL
accidentalidad$receso_mitad = NULL
accidentalidad$feria_flores = NULL
accidentalidad$receso_octubre = NULL
accidentalidad$vacaciones_final = NULL
accidentalidad$festivo_entre_semana = NULL
accidentalidad$no_festivo_importante = NULL

# Crear la variable accidentalidad, la cual corresponderá al numero de accidentes ocurridos durante ese día en cada barrio

accidentalidad$NUM_ACCIDENTES = ave(accidentalidad$FECHA, accidentalidad$BARRIO, FUN = length)
barrios = accidentalidad %>% distinct(COMUNA, BARRIO, .keep_all = TRUE)

heridos = c()
for (i in 1:nrow(barrios)) {
  row = barrios[i, ]
  heridos = c(heridos, nrow(accidentalidad[accidentalidad$GRAVEDAD=="HERIDO" & accidentalidad$BARRIO==row$BARRIO,]))
}
barrios$HERIDOS = heridos

atropellos = c()
for (i in 1:nrow(barrios)) {
  row = barrios[i, ]
  atropellos = c(atropellos, nrow(accidentalidad[accidentalidad$CLASE=="Atropello" & accidentalidad$BARRIO==row$BARRIO,]))
}
barrios$ATROPELLOS = atropellos

barrios$FECHA = NULL
barrios$CLASE = NULL
barrios$TIPO_GEOCOD = NULL
barrios$GRAVEDAD = NULL
barrios$DISENO = NULL
barrios$DIA_NOMBRE = NULL
barrios$MES_NOMBRE = NULL
barrios$FECHA_IMPORTANTE = NULL
```

```{r}
set.seed(19112020)
barrios_cluster = kmeans(barrios[, 3:5], 3)
```

```{r}
medio = barrios[factor(barrios_cluster$cluster) == "1", ]
medio
```

```{r}
bajo = barrios[factor(barrios_cluster$cluster) == "2", ]
bajo
```

```{r}
alto = barrios[factor(barrios_cluster$cluster) == "3", ]
alto
```

```{r}
riesgos = c()
for (i in 1:nrow(accidentalidad)) {
  b = nrow(bajo[bajo$BARRIO == accidentalidad[i,]$BARRIO,])
  m = nrow(medio[medio$BARRIO == accidentalidad[i,]$BARRIO,])
  a = nrow(alto[alto$BARRIO == accidentalidad[i,]$BARRIO,])
  if (b > 0) {
    riesgos = c(riesgos, "Bajo")
  } else if (m > 0) {
    riesgos = c(riesgos, "Medio")
  } else {
    riesgos = c(riesgos, "Alto")
  }
}
accidentalidad$RIESGO =  riesgos
```